export const data = {
    fr: {
        "presentation": "<span class='text-bolder'>Développeur étudiant</span> en 3e année de BUT informatique, passionné par la création de <span class='text-bolder'>sites web</span> et d'<span class='text-bolder'>applications</span>, prêt à céer le",
        "presentationHL": "<p id='presentation-futur-numerique'>Futur Numérique</p>",
        "text-parallelepiped": "Mes experiences professionnelles",
        "job-articles": [
            [
                "Allegro Microsystems",
                "Stagiaire développeur d'applications",
                "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque aperiam laborum magni debitis iure dolorem sed expedita temporibus? Fugiat rem, optio quae autem est temporibus enim quos praesentium sunt magni perferendis deleniti libero dolor reprehenderit soluta? Aperiam velit quidem, expedita autem commodi deserunt beatae, eum perferendis soluta iure odio debitis ab asperiores, amet reprehenderit natus laboriosam. Quis eos quos nemo incidunt impedit temporibus culpa ab ad. Minima et saepe dolore ullam natus molestias praesentium, tenetur culpa, modi velit accusantium maiores odio, voluptate repellat repudiandae! Ipsam assumenda soluta facere culpa nesciunt. Reiciendis eaque eius unde perspiciatis voluptatem totam, qui, similique et exercitationem corrupti tempora autem cumque facere dicta quisquam, ipsam nihil. Dolor iste perspiciatis illum? Facilis corrupti officiis in eveniet eius earum quia obcaecati, iure inventore aperiam illum blanditiis dicta incidunt laborum, quisquam magni eum necessitatibus fugiat harum voluptates molestias debitis praesentium? Sequi mollitia voluptates non repellendus reprehenderit incidunt perspiciatis, enim itaque tempora ullam nisi amet fuga fugit maiores ipsum harum est. Nostrum id animi voluptate incidunt ullam tempore ut provident repellendus architecto odit vel laborum omnis, aperiam accusamus temporibus soluta libero recusandae eius! Numquam minima praesentium error repellendus, perspiciatis, quam nihil, necessitatibus explicabo animi amet dolore quasi! Consequatur, non corrupti?"
            ],
            [
                "USMB - Projet d'étude",
                "Développeur de site e-commerce VueJS",
                "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque aperiam laborum magni debitis iure dolorem sed expedita temporibus? Fugiat rem, optio quae autem est temporibus enim quos praesentium sunt magni perferendis deleniti libero dolor reprehenderit soluta? Aperiam velit quidem, expedita autem commodi deserunt beatae, eum perferendis soluta iure odio debitis ab asperiores, amet reprehenderit natus laboriosam. Quis eos quos nemo incidunt impedit temporibus culpa ab ad. Minima et saepe dolore ullam natus molestias praesentium, tenetur culpa, modi velit accusantium maiores odio, voluptate repellat repudiandae! Ipsam assumenda soluta facere culpa nesciunt. Reiciendis eaque eius unde perspiciatis voluptatem totam, qui, similique et exercitationem corrupti tempora autem cumque facere dicta quisquam, ipsam nihil. Dolor iste perspiciatis illum? Facilis corrupti officiis in eveniet eius earum quia obcaecati, iure inventore aperiam illum blanditiis dicta incidunt laborum, quisquam magni eum necessitatibus fugiat harum voluptates molestias debitis praesentium? Sequi mollitia voluptates non repellendus reprehenderit incidunt perspiciatis, enim itaque tempora ullam nisi amet fuga fugit maiores ipsum harum est. Nostrum id animi voluptate incidunt ullam tempore ut provident repellendus architecto odit vel laborum omnis, aperiam accusamus temporibus soluta libero recusandae eius! Numquam minima praesentium error repellendus, perspiciatis, quam nihil, necessitatibus explicabo animi amet dolore quasi! Consequatur, non corrupti?"
            ],
            [
                "USMB - Projet d'étude",
                "Développeur de site e-commerce PHP",
                "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque aperiam laborum magni debitis iure dolorem sed expedita temporibus? Fugiat rem, optio quae autem est temporibus enim quos praesentium sunt magni perferendis deleniti libero dolor reprehenderit soluta? Aperiam velit quidem, expedita autem commodi deserunt beatae, eum perferendis soluta iure odio debitis ab asperiores, amet reprehenderit natus laboriosam. Quis eos quos nemo incidunt impedit temporibus culpa ab ad. Minima et saepe dolore ullam natus molestias praesentium, tenetur culpa, modi velit accusantium maiores odio, voluptate repellat repudiandae! Ipsam assumenda soluta facere culpa nesciunt. Reiciendis eaque eius unde perspiciatis voluptatem totam, qui, similique et exercitationem corrupti tempora autem cumque facere dicta quisquam, ipsam nihil. Dolor iste perspiciatis illum? Facilis corrupti officiis in eveniet eius earum quia obcaecati, iure inventore aperiam illum blanditiis dicta incidunt laborum, quisquam magni eum necessitatibus fugiat harum voluptates molestias debitis praesentium? Sequi mollitia voluptates non repellendus reprehenderit incidunt perspiciatis, enim itaque tempora ullam nisi amet fuga fugit maiores ipsum harum est. Nostrum id animi voluptate incidunt ullam tempore ut provident repellendus architecto odit vel laborum omnis, aperiam accusamus temporibus soluta libero recusandae eius! Numquam minima praesentium error repellendus, perspiciatis, quam nihil, necessitatibus explicabo animi amet dolore quasi! Consequatur, non corrupti?"
            ]
        ]
    },
    en: {
        "presentation": "Third-year <span class='text-bolder'>computer science student</span>, passionate about creating <span class='text-bolder'>websites</span> and <span class='text-bolder'>applications</span>, ready to shape the",
        "presentationHL": "<p id='presentation-futur-numerique'>Digital Future</p>",
        "text-parallelepiped": "My professional experience",
        "job-articles": 
        [
            [
                "Allegro Microsystems",
                "Application developer intern",
                "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque aperiam laborum magni debitis iure dolorem sed expedita temporibus? Fugiat rem, optio quae autem est temporibus enim quos praesentium sunt magni perferendis deleniti libero dolor reprehenderit soluta? Aperiam velit quidem, expedita autem commodi deserunt beatae, eum perferendis soluta iure odio debitis ab asperiores, amet reprehenderit natus laboriosam. Quis eos quos nemo incidunt impedit temporibus culpa ab ad. Minima et saepe dolore ullam natus molestias praesentium, tenetur culpa, modi velit accusantium maiores odio, voluptate repellat repudiandae! Ipsam assumenda soluta facere culpa nesciunt. Reiciendis eaque eius unde perspiciatis voluptatem totam, qui, similique et exercitationem corrupti tempora autem cumque facere dicta quisquam, ipsam nihil. Dolor iste perspiciatis illum? Facilis corrupti officiis in eveniet eius earum quia obcaecati, iure inventore aperiam illum blanditiis dicta incidunt laborum, quisquam magni eum necessitatibus fugiat harum voluptates molestias debitis praesentium? Sequi mollitia voluptates non repellendus reprehenderit incidunt perspiciatis, enim itaque tempora ullam nisi amet fuga fugit maiores ipsum harum est. Nostrum id animi voluptate incidunt ullam tempore ut provident repellendus architecto odit vel laborum omnis, aperiam accusamus temporibus soluta libero recusandae eius! Numquam minima praesentium error repellendus, perspiciatis, quam nihil, necessitatibus explicabo animi amet dolore quasi! Consequatur, non corrupti?"
            ],
            [
                "USMB - Study project",
                "VueJS e-commerce developer",
                "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque aperiam laborum magni debitis iure dolorem sed expedita temporibus? Fugiat rem, optio quae autem est temporibus enim quos praesentium sunt magni perferendis deleniti libero dolor reprehenderit soluta? Aperiam velit quidem, expedita autem commodi deserunt beatae, eum perferendis soluta iure odio debitis ab asperiores, amet reprehenderit natus laboriosam. Quis eos quos nemo incidunt impedit temporibus culpa ab ad. Minima et saepe dolore ullam natus molestias praesentium, tenetur culpa, modi velit accusantium maiores odio, voluptate repellat repudiandae! Ipsam assumenda soluta facere culpa nesciunt. Reiciendis eaque eius unde perspiciatis voluptatem totam, qui, similique et exercitationem corrupti tempora autem cumque facere dicta quisquam, ipsam nihil. Dolor iste perspiciatis illum? Facilis corrupti officiis in eveniet eius earum quia obcaecati, iure inventore aperiam illum blanditiis dicta incidunt laborum, quisquam magni eum necessitatibus fugiat harum voluptates molestias debitis praesentium? Sequi mollitia voluptates non repellendus reprehenderit incidunt perspiciatis, enim itaque tempora ullam nisi amet fuga fugit maiores ipsum harum est. Nostrum id animi voluptate incidunt ullam tempore ut provident repellendus architecto odit vel laborum omnis, aperiam accusamus temporibus soluta libero recusandae eius! Numquam minima praesentium error repellendus, perspiciatis, quam nihil, necessitatibus explicabo animi amet dolore quasi! Consequatur, non corrupti?"
            ],
            [
                "USMB - Projet d'étude",
                "PHP e-commerce developer",
                "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque aperiam laborum magni debitis iure dolorem sed expedita temporibus? Fugiat rem, optio quae autem est temporibus enim quos praesentium sunt magni perferendis deleniti libero dolor reprehenderit soluta? Aperiam velit quidem, expedita autem commodi deserunt beatae, eum perferendis soluta iure odio debitis ab asperiores, amet reprehenderit natus laboriosam. Quis eos quos nemo incidunt impedit temporibus culpa ab ad. Minima et saepe dolore ullam natus molestias praesentium, tenetur culpa, modi velit accusantium maiores odio, voluptate repellat repudiandae! Ipsam assumenda soluta facere culpa nesciunt. Reiciendis eaque eius unde perspiciatis voluptatem totam, qui, similique et exercitationem corrupti tempora autem cumque facere dicta quisquam, ipsam nihil. Dolor iste perspiciatis illum? Facilis corrupti officiis in eveniet eius earum quia obcaecati, iure inventore aperiam illum blanditiis dicta incidunt laborum, quisquam magni eum necessitatibus fugiat harum voluptates molestias debitis praesentium? Sequi mollitia voluptates non repellendus reprehenderit incidunt perspiciatis, enim itaque tempora ullam nisi amet fuga fugit maiores ipsum harum est. Nostrum id animi voluptate incidunt ullam tempore ut provident repellendus architecto odit vel laborum omnis, aperiam accusamus temporibus soluta libero recusandae eius! Numquam minima praesentium error repellendus, perspiciatis, quam nihil, necessitatibus explicabo animi amet dolore quasi! Consequatur, non corrupti?"
            ]
        ]
    }
}